version: 2.1
jobs:
  build-linux:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
        name: Install python3
        command: |
          sudo apt install python3-pip
          pip3 install pyinstaller
      - run: Build source
        working_directory: src
        command: |
          pyinstaller AutoPagePdf.py
          ls -al

workflows:
  version: 2.1
  openvpn-pipeline:
    jobs:
      - build-linux
