version: 2.1
orbs:
  win: circleci/windows@4.1.1
jobs:
  build-windows:
    executor: win/server-2022
    steps:
      - checkout
      - run:
          name: Install python3
          command: |
            Set-ExecutionPolicy -Scope CurrentUser
            $script = New-Object Net.WebClient
            $script.DownloadString("https://chocolatey.org/install.ps1")
            iwr https://chocolatey.org/install.ps1 -UseBasicParsing | iex
            choco install -y python3
            pip3 install pyinstaller awscli
      - run:
          name: Build source
          working_directory: src
          command: |
            pyinstaller.exe --onefile AutoPagePdf.py
            New-Item AutoPagePdf_windows -ItemType Directory
            Copy-Item .\dist\AutoPagePdf.exe .\AutoPagePdf_windows\
            Copy-Item .\config.json .\AutoPagePdf_windows\
            Compress-Archive .\AutoPagePdf_windows\ AutoPagePdf_windows.zip
            aws s3 cp .\AutoPagePdf_windows.zip s3://autopagepdf.tuimac.com/downloads/windows/AutoPagePdf_windows.zip
  build-linux:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: Install python3
          command: |
            sudo apt install python3-pip
            pip3 install pyinstaller awscli
      - run:
          name: Build source
          working_directory: src
          command: |
            pyinstaller --onefile AutoPagePdf.py
            mkdir AutoPagePdf_linux
            cp config.json AutoPagePdf_linux
            cp dist/AutoPagePdf AutoPagePdf_linux
            zip -r AutoPagePdf_linux.zip AutoPagePdf_linux/
            aws s3 cp AutoPagePdf_linux.zip s3://autopagepdf.tuimac.com/downloads/linux/AutoPagePdf_linux.zip
  build-mac:
    macos:
      xcode: 13.4.1
    steps:
      - checkout
      - run:
          name: Install python3
          command: |
            brew install python
            pip3 install pyinstaller awscli           
      - run:
          name: Build source
          working_directory: src
          command: |
            pyinstaller --onefile AutoPagePdf.py
            mkdir AutoPagePdf_linux
            cp config.json AutoPagePdf_mac
            cp dist/AutoPagePdf AutoPagePdf_mac
            zip -r AutoPagePdf_mac.zip . -i AutoPagePdf_mac/
            aws s3 cp AutoPagePdf_mac.zip s3://autopagepdf.tuimac.com/downloads/mac/AutoPagePdf_mac.zip
  upload-homepage:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: Install python3
          command: |
            sudo apt install python3-pip
            pip3 install pyinstaller awscli
      - run:
          name: Build source
          working_directory: download
          command: |
            aws s3 cp index.html s3://autopagepdf.tuimac.com/index.html
workflows:
  version: 2.1
  autopagepdf-pipeline:
    jobs:
      - build-windows
      - build-linux:
          requires:
            - build-windows
      - build-mac:
          requires:
            - build-linux
      - upload-homepage:
          requires:
            - build-mac
